- hosts: localhost
  roles:
    - { role: abessifi.java }
    - { role: geerlingguy.jenkins, jenkins_hostname: localhost }
  tasks:
  - name: Install git 
    sudo: yes
    apt:
     name: git
     state: installed
     update_cache: yes
