- hosts: localhost
   roles:
    - { role: geerlingguy.java }
    - { role: geerlingguy.jenkins, jenkins_hostname: localhost }
   name: Install git 
   apt:
    name: git
    state: installed
    update_cache: yes
    sudo: yes
