- hosts: localhost
  sudo: yes
  tasks:
  - name: install prometheus
    unarchive:
     src: https://github.com/prometheus/prometheus/releases/download/v1.1.3/prometheus-1.1.3.linux-amd64.tar.gz
     dest: /Prometheus
     copy: no

  - name: install node-exporter
    unarchive:
     src: https://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
     dest: /Prometheus

  - name: run node exporter as an init service
    copy:
     src: ./files/node_exporter.service
     dest: /etc/systemd/system/node_exporter.service

  - name: reload systemd
    shell: systemctl daemon-reload

  - name: enable node exporter service
    shell: systemctl enable node_exporter.service

  - name: start node exporter service
    shell: systemctl start node_exporter.service
  
  - name: update prometheus configuration
    copy:
      src: ./files/prometheus.yml
      dest: /etc/prometheus/prometheus.yml

  - name: run prometheus
    shell: ./prometheus -storage.local.memory-chunks=10000
    args:
     chdir: /Prometheus

  - name: install grafana dependencies
    apt:
     name: "{{ item }}"
     state: installed
    with_items:
     - apt-transport-https
     - ufw

  - name: add GPG key
    apt_key:
      url:  https://packagecloud.io/gpg.key
      state: present

  - name: add repository
    apt_repository:
      repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
      state: present
      filename: grafana

  - name: install grafana
    apt:
     name: grafana
     state: installed

  - name: run grafana as an init service
    shell: update-rc.d grafana-server defaults 95 10

  - name: allow grafana port in UFW
    ufw:
     rule: allow
     port: 3000
     proto: tcp

  - name: start grafana service
    service:
     name: grafana-server
     state: started      
~                                               
