apiVersion: batch/v1
kind: Job
metadata:
  name: microservice3-job
spec:
  template:
    metadata:
      name: microservice3-job
    spec:
      containers:
      - name: microservice3-job
        image: gcr.io/robust-root-125814/microservice3-job
      restartPolicy: Never
