apiVersion:  extensions/v1beta1
kind: Deployment
metadata:
  name: microservice2-deployment
  namespace: dev-namespace
  labels:
    app: microservice2
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2-container
        image: sbouii/python-microservice2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          hostPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: microservice2-service
  labels:
    app: microservice2 
  spec:
    type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: microservice2
