apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-microservice2
  namespace: dev-namespace  
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pod: "2"
