apiVersion:  extensions/v1beta1
kind: Deployment
metadata:
  name: microservice1-deployment
  labels:
    app: microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1-container
        image: sbouii/python-microservice1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi 
        ports:
        - containerPort: 80
          hostPort: 80
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        hostPath:
         path: /microservice1-data   
---
apiVersion: v1
kind: Service
metadata:
  name: microservice1-service
  labels:
    app: microservice1
spec:
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
  selector:
   app: microservice1
